try add post-build gmp step

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,6 +34,7 @@ jobs:
 
       - name: Set environment variables
         run: |
+          echo "TARGET=${{ matrix.os }}-${{ matrix.arch }}" >> $GITHUB_ENV
           case "${{ matrix.os }}-${{ matrix.arch }}" in
             "linux-x64")
               echo "HOST=x86_64-pc-linux-gnu" >> $GITHUB_ENV
@@ -109,7 +110,6 @@ jobs:
 
       - name: Install Toolchain (arch-specific)
         run: |
-          TARGET="${{ matrix.os }}-${{ matrix.arch }}"
           case "$TARGET" in
             "linux-x86")
               sudo apt-get update
@@ -172,6 +172,38 @@ jobs:
           ls -l
           file ${{ env.GMP_SO }}
 
+      - name: Post-Build GMP
+        run: |
+          case "$TARGET" in
+            win-*)
+              if [ "$TARGET" = "win-x86" ]; then
+                HOST_PREFIX=i686-w64-mingw32
+              else if [ "$TARGET" = "win-x64" ]; then
+                HOST_PREFIX=x86_64-w64-mingw32
+              else
+                echo "Error: Unsupported OS-Architecture combination: $TARGET"
+                exit 1
+              fi
+
+              cd gmp-${GMP_VERSION}/.libs
+
+              ${HOST_PREFIX}-dlltool \
+                --input-def libgmp-3.dll.def \
+                --output-lib libgmp-10.lib \
+                --dllname libgmp-10.dll
+                
+              ${HOST_PREFIX}-dlltool \
+                --input-def libgmpxx-3.dll.def \
+                --output-lib libgmpxx-4.lib \
+                --dllname libgmpxx-4.dll
+
+              echo "Converted .def files to .lib for Windows."
+              ;;
+            *)
+              echo "Nothing to do for $TARGET"
+              ;;
+          esac
+
       - name: Strip GMP Library
         run: |
           cd gmp-${GMP_VERSION}/.libs
@@ -192,7 +224,6 @@ jobs:
       - name: Run Test C Program
         if: ${{ matrix.os != 'android' }}
         run: |
-          TARGET="${{ matrix.os }}-${{ matrix.arch }}"
           case "$TARGET" in
             win-*)
               cp ${{ github.workspace }}/gmp-${GMP_VERSION}/.libs/${{ env.GMP_SO }} .
@@ -220,6 +251,6 @@ jobs:
           path: |
             gmp-${{ env.GMP_VERSION }}/gmp.h
             gmp-${{ env.GMP_VERSION }}/gmpxx.h
+            gmp-${{ env.GMP_VERSION }}/.libs/*.def
             gmp-${{ env.GMP_VERSION }}/.libs/${{ env.GMP_SO }}
             gmp-${{ env.GMP_VERSION }}/.libs/${{ env.GMP_CPP_SO }}
-            gmp-${{ env.GMP_VERSION }}/.libs/*.def
